using System.Text;
using HomeAssistant.Application.Dispatching;
using HomeAssistant.Application.GardenAdvisor.Abstractions;
using HomeAssistant.Application.GardenAdvisor.Contracts.Advice;
using HomeAssistant.Application.PotConfigurations.Abstractions;
using HomeAssistant.Application.PotConfigurations.Commands;
using HomeAssistant.Application.PotConfigurations.DTOs;
using HomeAssistant.Application.PotConfigurations.Queries;
using HomeAssistant.Domain.Common.Handlers;
using HomeAssistant.Domain.PotConfigurations.Abstractions;
using HomeAssistant.Domain.SensorReadings.Abstractions;
using HomeAssistant.Presentation.Garden.Abstractions;
using HomeAssistant.Presentation.Garden.Contracts;
using HomeAssistant.Presentation.Garden.Planner.Functions.Contracts;
using AppGardenAdviceResponse = HomeAssistant.Application.GardenAdvisor.Contracts.Advice.GardenAdviceResponse;
using PresentationSavePotConfigurationRequest = HomeAssistant.Presentation.Garden.Planner.Functions.Contracts.SavePotConfigurationRequest;
using SavePotConfigurationCommandRequest = HomeAssistant.Application.PotConfigurations.Commands.SavePotConfigurationRequest;
using SeedAssignmentCommandRequest = HomeAssistant.Application.PotConfigurations.Commands.SeedAssignmentRequest;
namespace HomeAssistant.Presentation.Garden.Services;
public sealed class GardenPlannerToolService : IGardenPlannerToolService
{
    private readonly IPotIdentityMapProvider _potIdentityMapProvider;
    private readonly IPotConfigurationRepository _potRepository;
    private readonly ISensorReadingRepository _sensorRepository;
    private readonly ICommandDispatcher _commandDispatcher;
    private readonly IQueryHandler<GetDashboardAggregationQuery, DashboardAggregationDto> _dashboardHandler;
    private readonly IQueryHandler<GetRoomSummaryQuery, RoomSummaryDto> _roomSummaryHandler;
    private readonly IQueryHandler<GetHarvestReadinessQuery, IReadOnlyList<HarvestReadinessDto>> _harvestReadinessHandler;
    private readonly IHomeAssistantAreaProvider _areaProvider;
    private readonly IGardenAdviceStateStore _adviceStateStore;
    private readonly IGardenAdvisorService _gardenAdvisorService;
    private readonly IGardenPlannerHistoryStore _historyStore;
    private readonly ILogger<GardenPlannerToolService> _logger;
    public GardenPlannerToolService(IPotIdentityMapProvider potIdentityMapProvider, IPotConfigurationRepository potRepository, ISensorReadingRepository sensorRepository, ICommandDispatcher commandDispatcher, IQueryHandler<GetDashboardAggregationQuery, DashboardAggregationDto> dashboardHandler, IQueryHandler<GetRoomSummaryQuery, RoomSummaryDto> roomSummaryHandler, IQueryHandler<GetHarvestReadinessQuery, IReadOnlyList<HarvestReadinessDto>> harvestReadinessHandler, IHomeAssistantAreaProvider areaProvider, IGardenAdviceStateStore adviceStateStore, IGardenAdvisorService gardenAdvisorService, IGardenPlannerHistoryStore historyStore, ILogger<GardenPlannerToolService> logger) { _potIdentityMapProvider = potIdentityMapProvider ?? throw new ArgumentNullException(nameof(potIdentityMapProvider)); _potRepository = potRepository ?? throw new ArgumentNullException(nameof(potRepository)); _sensorRepository = sensorRepository ?? throw new ArgumentNullException(nameof(sensorRepository)); _commandDispatcher = commandDispatcher ?? throw new ArgumentNullException(nameof(commandDispatcher)); _dashboardHandler = dashboardHandler ?? throw new ArgumentNullException(nameof(dashboardHandler)); _roomSummaryHandler = roomSummaryHandler ?? throw new ArgumentNullException(nameof(roomSummaryHandler)); _harvestReadinessHandler = harvestReadinessHandler ?? throw new ArgumentNullException(nameof(harvestReadinessHandler)); _areaProvider = areaProvider ?? throw new ArgumentNullException(nameof(areaProvider)); _adviceStateStore = adviceStateStore ?? throw new ArgumentNullException(nameof(adviceStateStore)); _gardenAdvisorService = gardenAdvisorService ?? throw new ArgumentNullException(nameof(gardenAdvisorService)); _historyStore = historyStore ?? throw new ArgumentNullException(nameof(historyStore)); _logger = logger ?? throw new ArgumentNullException(nameof(logger)); }
    public async Task<string> SavePotConfigurationAsync(PresentationSavePotConfigurationRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); var potId = await _potIdentityMapProvider.ResolvePotIdAsync(request.PotNumber, ct); if (!potId.HasValue) return "Invalid pot number. Use a configured pot number from PotIdentityMap."; if (string.IsNullOrWhiteSpace(request.PlantName) || string.IsNullOrWhiteSpace(request.SeedName)) return "Plant name and seed name are required."; var roomName = request.RoomAreaId switch { "balcony" => "Balcony", "greenhouse" => "Greenhouse", _ => "Living Room", }; await _commandDispatcher.DispatchAsync(new SavePotConfigurationCommand(potId.Value, new SavePotConfigurationCommandRequest(request.RoomAreaId, roomName, [new SeedAssignmentCommandRequest(request.PlantName, request.SeedName, request.PlantedDate ?? DateTimeOffset.UtcNow, null, request.Status, request.Notes)])), ct); _logger.LogInformation("Planner tool saved pot configuration for pot {PotNumber} ({PlantName}/{SeedName}).", request.PotNumber, request.PlantName, request.SeedName); return $"? Saved {request.PlantName} ({request.SeedName}) in Pot {request.PotNumber} ({roomName}), status: {request.Status}."; }
    public async Task<string> UpdateSeedStatusAsync(UpdateSeedStatusRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); var potId = await _potIdentityMapProvider.ResolvePotIdAsync(request.PotNumber, ct); if (!potId.HasValue) return "Invalid pot number. Use a configured pot number from PotIdentityMap."; var config = await _potRepository.GetByPotIdAsync(potId.Value, ct); if (config is null) return $"Pot {request.PotNumber} has no configuration."; var seed = config.CurrentSeeds.FirstOrDefault(s => s.Status == "growing") ?? config.CurrentSeeds.FirstOrDefault(); if (seed is null) return $"Pot {request.PotNumber} has no seeds to update."; await _commandDispatcher.DispatchAsync(new UpdateSeedStatusCommand(potId.Value, seed.Id, request.NewStatus), ct); _logger.LogInformation("Planner tool updated seed status for pot {PotNumber} to {Status}.", request.PotNumber, request.NewStatus); return $"? Pot {request.PotNumber} ({seed.PlantName}/{seed.SeedName}) status ? '{request.NewStatus}'."; }
    public async Task<string> GetPotStatusAsync(PotNumberRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); var potId = await _potIdentityMapProvider.ResolvePotIdAsync(request.PotNumber, ct); if (!potId.HasValue) return "Invalid pot number. Use a configured pot number from PotIdentityMap."; var config = await _potRepository.GetByPotIdAsync(potId.Value, ct); var reading = await _sensorRepository.GetLatestByPotAsync(potId.Value, ct); if (config is null) return $"Pot {request.PotNumber}: no configuration yet. {FormatReading(reading)}."; var seeds = config.CurrentSeeds.Count > 0 ? string.Join(", ", config.CurrentSeeds.Select(s => $"{s.PlantName}/{s.SeedName} ({s.Status})")) : "empty"; return $"Pot {request.PotNumber} [{config.RoomName}]: {seeds}. {FormatReading(reading)}."; }
    public async Task<string> GetAllPotsStatusAsync(CancellationToken ct = default) { var configs = await _potRepository.GetAllAsync(ct); var configByPot = configs.ToDictionary(c => c.PotId); var map = await _potIdentityMapProvider.GetMapAsync(ct); var sb = new StringBuilder(); foreach (var (potNumber, potId) in map.OrderBy(kv => kv.Key)) { configByPot.TryGetValue(potId, out var config); var reading = await _sensorRepository.GetLatestByPotAsync(potId, ct); var seed = config?.CurrentSeeds.FirstOrDefault(s => s.Status == "growing") ?? config?.CurrentSeeds.FirstOrDefault(); sb.AppendLine($"Pot {potNumber} [{config?.RoomName ?? "unassigned"}]: {seed?.PlantName ?? "empty"}{(seed is not null ? $"/{seed.SeedName} ({seed.Status})" : string.Empty)}. {FormatReading(reading)}."); } return sb.ToString().TrimEnd(); }
    public async Task<string> GetSensorReadingsAsync(PotNumberRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); var potId = await _potIdentityMapProvider.ResolvePotIdAsync(request.PotNumber, ct); if (!potId.HasValue) return "Invalid pot number. Use a configured pot number from PotIdentityMap."; var reading = await _sensorRepository.GetLatestByPotAsync(potId.Value, ct); return reading is null ? $"Pot {request.PotNumber}: no sensor data yet." : $"Pot {request.PotNumber}: moisture {reading.SoilMoisture:0.0}%, temperature {reading.TemperatureC:0.0}�C ({reading.Timestamp:HH:mm} UTC)."; }
    public Task<IReadOnlyList<RoomResponse>> GetAvailableRoomsAsync(CancellationToken ct = default) => _areaProvider.GetAvailableRoomsAsync(ct);
    public async Task<RoomSummaryResponse> GetRoomSummaryAsync(RoomAreaRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); ArgumentException.ThrowIfNullOrWhiteSpace(request.RoomAreaId); var dto = await _roomSummaryHandler.HandleAsync(new GetRoomSummaryQuery(request.RoomAreaId), ct); return RoomSummaryResponse.FromDto(dto); }
    public async Task<DashboardAggregationResponse> GetDashboardAsync(CancellationToken ct = default) { var dto = await _dashboardHandler.HandleAsync(new GetDashboardAggregationQuery(), ct); return DashboardAggregationResponse.FromDto(dto); }
    public async Task<IReadOnlyList<HarvestReadinessResponse>> GetHarvestReadinessAsync(HarvestReadinessRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); var dtos = await _harvestReadinessHandler.HandleAsync(new GetHarvestReadinessQuery(request.FilterByStatus), ct); return dtos.Select(HarvestReadinessResponse.FromDto).ToList().AsReadOnly(); }
    public AppGardenAdviceResponse? GetLatestAdvice() => _adviceStateStore.GetLatest();
    public Task<AppGardenAdviceResponse> GenerateAdviceAsync(GenerateAdviceRequest request, CancellationToken ct = default) { ArgumentNullException.ThrowIfNull(request); return _gardenAdvisorService.GenerateAdviceAsync(request.PublishToMqtt, ct); }
    public string ClearPlannerHistory() { _historyStore.Clear(); _logger.LogInformation("Planner tool cleared in-memory chat history."); return "? Planner history cleared."; }
    private static string FormatReading(Domain.SensorReadings.Entities.SensorReading? reading) => reading is null ? "no sensor data" : $"moisture {reading.SoilMoisture:0.0}%, temp {reading.TemperatureC:0.0}�C";
}
